# ===== SERVER =====
server.port=8080
server.address=0.0.0.0
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=15s
spring.application.name=chat-application

# ===== MONGODB =====
spring.data.mongodb.uri=mongodb://localhost:27017/chatapp
spring.data.mongodb.database=chatapp

# ===== FILE UPLOAD =====
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
file.upload-dir=uploads

# ===== ADMIN CREDENTIALS =====
admin.username=admin
admin.password=Admin@12345

# ===== GOOGLE OAUTH2 =====
# Get these from https://console.cloud.google.com/apis/credentials
spring.security.oauth2.client.registration.google.client-id=351903559829-ia3cuuaruq0vphkpact7j5f38di32sml.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# ===== LOGGING =====
logging.level.com.chat.app=DEBUG
app.crypto.aesKeyBase64=lCXFeR1eCAV3WshakuHL3TA2rz0ypZyV92s4gqVgQpY=